export const Data = [
  {
    title: "Breakfast meal",
    description: "hop you like this breakfast meal",
    price:115,
    category:"Breakfast",
    img: require("../Assets/food1.jpg"),
  },
  {
    title: "Breakfast meal",
    description: "hop you like this breakfast meal",
    price:30,
    category:"Breakfast",
    img: require("../Assets/food2.jpg"),
  },
  {
    title: "Breakfast meal",
    description: "hop you like this breakfast meal",
    price:50,
    category:"Breakfast",
    img: require("../Assets/food3.jpg"),
  },
  {
    title: "lunch meal",
    description: "hop you like this lunch meal",
    price:38,
    category:"lunch",
    img: require("../Assets/food1.jpg"),
  },
  {
    title: "lunch meal",
    description: "hop you like this lunch meal",
    price:100,
    category:"lunch",
    img: require("../Assets/food2.jpg"),
  },
  {
    title: "lunch meal",
    description: "hop you like this lunch meal",
    price:70,
    category:"lunch",
    img: require("../Assets/food3.jpg"),
  },
  {
    title: "Dinner meal",
    description: "hop you like this Dinner meal",
    price:90,
    category:"Dinner",
    img: require("../Assets/food1.jpg"),
  },
  {
    title: "Dinner meal",
    description: "hop you like this Dinner meal",
    price:51,
    category:"Dinner",
    img: require("../Assets/food2.jpg"),
  },
  {
    title: "Dinner meal",
    description: "hop you like this Dinner meal",
    price:63,
    category:"Dinner",
    img: require("../Assets/food3.jpg"),
  },
];